# Generated by Django 2.0.13 on 2020-10-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Id_Administrador', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Completo', models.CharField(max_length=40)),
                ('Cargo', models.CharField(max_length=30)),
                ('Genero', models.CharField(max_length=2)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=60)),
                ('Codigo_Postal', models.IntegerField()),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Grupo_Sanguineo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('Id_Clase', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Academicos',
            fields=[
                ('Matricula', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('Grado', models.IntegerField()),
                ('Grupo', models.CharField(max_length=2)),
                ('Inscrito', models.CharField(max_length=2)),
                ('Estatus', models.CharField(max_length=10)),
                ('Promedio_General', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Docente',
            fields=[
                ('Cedula_Personal', models.AutoField(primary_key=True, serialize=False)),
                ('Cargo', models.CharField(max_length=30)),
                ('Disciplinas_Asignadas', models.CharField(max_length=30)),
                ('Tutorado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Personales',
            fields=[
                ('Id_Personales', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido_Paterno', models.CharField(max_length=20)),
                ('Apellido_Materno', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
                ('Genero', models.CharField(max_length=2)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=40)),
                ('Codigo_Postal', models.IntegerField()),
                ('CURP', models.CharField(max_length=20)),
                ('Fecha_Nacimiento', models.DateTimeField()),
                ('Lugar_Nacimiento', models.CharField(max_length=40)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Grupo_Sanguineo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Personales_Docente',
            fields=[
                ('Id_Personales_Docente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Completo', models.CharField(max_length=60)),
                ('Genero', models.CharField(max_length=2)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=60)),
                ('Codigo_Postal', models.IntegerField()),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Grupo_Sanguineo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Procedencia',
            fields=[
                ('Id_Procedencia', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel_Basico', models.CharField(max_length=20)),
                ('Año_Egreso', models.IntegerField()),
                ('Promedio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('Clave_Disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Acreditacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Cursadas',
            fields=[
                ('Id_Cursadas', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Clave_Discipina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Cursando',
            fields=[
                ('Id_Cursando', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Grado', models.IntegerField()),
                ('Grupo', models.CharField(max_length=2)),
                ('Clave_Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Por_Cursar',
            fields=[
                ('Id_PorCursar', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Grado', models.IntegerField()),
                ('Clave_Discipina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Id_Docente', models.AutoField(primary_key=True, serialize=False)),
                ('Cedula_Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Docente')),
                ('Clave_Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas')),
                ('Id_Personales_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Personales_Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Id_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Cursando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas_Cursando')),
                ('Id_Personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Personales')),
                ('Id_Procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Procedencia')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Id_Login', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_Tutor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Completo', models.CharField(max_length=40)),
                ('Direccion', models.CharField(max_length=40)),
                ('Telefono', models.IntegerField()),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Academicos')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Id_Tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Tutor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Datos_Academicos'),
        ),
        migrations.AddField(
            model_name='datos_academicos',
            name='Id_Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Estudiante'),
        ),
        migrations.AddField(
            model_name='clase',
            name='Clave_Disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Disciplinas'),
        ),
        migrations.AddField(
            model_name='clase',
            name='Id_Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Docente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='Id_Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.Estudiante'),
        ),
    ]
