# Generated by Django 3.1.3 on 2020-11-30 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Aspirantes',
            fields=[
                ('Id_Personales', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido_Paterno', models.CharField(max_length=20)),
                ('Apellido_Materno', models.CharField(max_length=20)),
                ('Cargo', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
                ('Genero', models.CharField(max_length=2)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=40)),
                ('Codigo_Postal', models.IntegerField()),
                ('CURP', models.CharField(max_length=20)),
                ('Fecha_Nacimiento', models.DateField(max_length=40)),
                ('Lugar_Nacimiento', models.CharField(max_length=40)),
                ('Correo_Electronico', models.EmailField(max_length=254)),
                ('Grupo_Sanguineo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Procedencia',
            fields=[
                ('Id_Procedencia', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nivel_Basico', models.CharField(max_length=20)),
                ('Año_Egreso', models.IntegerField()),
                ('Promedio_General', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Id_Aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.datos_aspirantes')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('Id_Disciplina', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre_Disciplina', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Cursadas',
            fields=[
                ('Id_Cursadas', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre_Cursadas', models.CharField(max_length=30)),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Id_Discipina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Cursando',
            fields=[
                ('Id_Cursando', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Momento1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Momento2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Momento3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Id_Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Id_Login', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('Id_Tutor', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre_Tutor', models.CharField(max_length=40)),
                ('Direccion_Tutor', models.CharField(max_length=40)),
                ('Telefono_Tutor', models.IntegerField()),
                ('Id_Aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.datos_aspirantes')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Grado', models.IntegerField()),
                ('Grupo', models.CharField(max_length=2)),
                ('Inscrito', models.CharField(max_length=2)),
                ('Estatus', models.CharField(max_length=10)),
                ('Promedio_General', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Id_Cursadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.disciplinas_cursadas')),
                ('Id_Cursando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.disciplinas_cursando')),
                ('Id_Procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.datos_procedencia')),
                ('Id_Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Cedula_Profesional', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Grupo_Tutorado', models.CharField(max_length=30)),
                ('Id_Aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.datos_aspirantes')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('Id_Clase', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre_Clase', models.CharField(max_length=30)),
                ('Id_Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.disciplinas')),
                ('Id_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Id_Administrador', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Id_Personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_SCIA.datos_aspirantes')),
            ],
        ),
    ]
