# Generated by Django 2.0.13 on 2020-10-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_personales_docente',
            old_name='Direccion',
            new_name='DireccionD',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='Direccion',
            new_name='DireccionT',
        ),
    ]
