# Generated by Django 3.1.3 on 2020-12-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinas_cursando',
            old_name='Momento1',
            new_name='Momento',
        ),
        migrations.RemoveField(
            model_name='disciplinas_cursando',
            name='Momento2',
        ),
        migrations.RemoveField(
            model_name='disciplinas_cursando',
            name='Momento3',
        ),
    ]
