# Generated by Django 3.1.3 on 2020-11-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='DireccionT',
            new_name='Direccion_Tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='TelefonoT',
            new_name='Telefono_Tutor',
        ),
    ]
