# Generated by Django 3.1.3 on 2020-12-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0002_auto_20201207_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinas_cursadas',
            old_name='Id_Discipina',
            new_name='Id_Disciplina',
        ),
    ]
