# Generated by Django 3.1.3 on 2020-11-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0002_auto_20201129_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_procedencia',
            old_name='Promedio',
            new_name='Promedio_General',
        ),
    ]
