# Generated by Django 3.1.3 on 2020-12-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0003_auto_20201209_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='Id_Cursadas',
        ),
        migrations.DeleteModel(
            name='Disciplinas_Cursadas',
        ),
    ]
