# Generated by Django 3.1.3 on 2020-12-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0004_auto_20201221_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Matricula',
            new_name='NIA',
        ),
    ]
