# Generated by Django 3.1.3 on 2020-12-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_SCIA', '0005_auto_20201222_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='NIA',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
