from .administrador import Administrador
from .clase import Clase
from .disciplinas import Disciplinas
from .disciplinas_cursadas import Disciplinas_Cursadas
from .docente import Docente
from .datos_aspirantes import Datos_Aspirantes
from .datos_procedencia import Datos_Procedencia
from .disciplinas_cursando import Disciplinas_Cursando
from .estudiante import Estudiante
from .login import Login
from .tutor import Tutor