from .administrador import Administrador
from .clase import Clase
from .datos_docente import Administrador
from .datos_personales_docente import Datos_Personales_Docente
from .disciplinas import Disciplinas
from .disciplinas_cursadas import Disciplinas_Cursadas
from .disciplinas_por_cursadas import Disciplinas_Por_Cursadas
from .docente import Docente
from .datos_academicos import Datos_Academicos 
from .datos_personales import Datos_Personales
from .datos_procedencia import Datos_Procedencia
from .disciplinas_cursando import Disciplinas_Cursando
from .estudiante import Estudiante
from .login import Login
from .tutor import Tutor
